services:
  backup-manager-s3:
    container_name: backup-manager-s3
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - minio:/minio_data
      - ./certs/minio:/root/.minio/certs
    command: minio server /minio_data --console-address ":9001" --address ":9000" --certs-dir "/root/.minio/certs"
    networks:
      - backup-network
    healthcheck:
      test: [ "CMD", "curl", "-k", "-f", "https://localhost:9000/minio/health/live" ]
      interval: 3s
      timeout: 20s
      retries: 3
  createbucket:
    image: minio/mc
    environment:
      MINIO_HOST: https://backup-manager-s3:9000
      MINIO_USER: minioadmin
      MINIO_PASSWORD: minioadmin
    networks:
      - backup-network
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio-s3 $${MINIO_HOST} $${MINIO_USER} $${MINIO_PASSWORD} --insecure;
      /usr/bin/mc mb minio-s3/pgbackrest --ignore-existing --insecure;
      /usr/bin/mc anonymous set public minio-s3/pgbackrest --insecure;
      exit 0;
      "
    depends_on:
      backup-manager-s3:
        condition: service_healthy
networks:
  backup-network:
    driver: bridge
volumes:
  minio: