services:
  backup-manager-s3:
    container_name: backup-manager-s3
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/minio:/minio_data
      - ./certs:/root/.minio/certs
    command: minio server /minio_data --console-address ":9001" --address ":9000" --certs-dir "/root/.minio/certs"
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD", "curl", "-k", "-f", "https://localhost:9000/minio/health/live" ]
      interval: 3s
      timeout: 20s
      retries: 3
networks:
  mynetwork:
    driver: bridge