name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64
        driver-opts: |
          image=moby/buildkit:master
          network=host

    - name: Create certificates directory
      run: mkdir -p certs

    - name: Make test script executable
      run: chmod +x test-scripts/run_unit_tests.sh

    - name: Run tests
      run: ./test-scripts/run_unit_tests.sh
  integration-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64
        driver-opts: |
          image=moby/buildkit:master
          network=host

    - name: Install necessary packages
      run: sudo apt update && sudo apt install -y openssh-client libssl-dev

    - name: Create ssh_keys directory
      run: mkdir -p ssh_keys

    - name: Generate SSH keys for postgres
      run: |
        ssh-keygen -t rsa -b 4096 -f ssh_keys/id_rsa_postgres -N ""
        chmod 600 ssh_keys/id_rsa_postgres

    - name: Generate SSH keys for backup manager
      run: |
        ssh-keygen -t rsa -b 4096 -f ssh_keys/id_rsa_backup_manager -N ""
        chmod 600 ssh_keys/id_rsa_backup_manager

    - name: Create certificates directory
      run: mkdir -p certs

    - name: Generate SSL certificates
      run: |
        openssl genpkey -algorithm RSA -out certs/private.key -pkeyopt rsa_keygen_bits:2048
        openssl req -new -x509 -key certs/private.key -out certs/public.crt -days 3650 -subj "/CN=minio"
        chmod 600 certs/private.key
        chmod 644 certs/public.crt

    - name: Make test script executable
      run: chmod +x test-scripts/run_integration_tests.sh

    - name: Run tests
      run: ./test-scripts/run_integration_tests.sh